version: 2

run:
  go: '1.21'
  timeout: 10m

linters:
  enable:
    - gofumpt
    - thelper
    - goimports
    - tparallel
    - wastedassign
    - copyloopvar
    - unparam
    - prealloc
    - unconvert
    - exhaustive
    - makezero
    - nakedret
    # - goconst # TODO: enable and fix issues

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true

  nakedret:
    # the gods will judge me but I just don't like naked returns at all
    max-func-lines: 0

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
